/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Number of SMS messages in the inbox that have an unread status. */
@org.apache.avro.specific.AvroGenerated
public class PhoneSmsUnread extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8741314777358443357L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneSmsUnread\",\"namespace\":\"org.radarcns.phone\",\"doc\":\"Number of SMS messages in the inbox that have an unread status.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"unreadSMS\",\"type\":\"int\",\"doc\":\"number of unread SMS messages currently in the inbox\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** number of unread SMS messages currently in the inbox */
  @Deprecated public int unreadSMS;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhoneSmsUnread() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param unreadSMS number of unread SMS messages currently in the inbox
   */
  public PhoneSmsUnread(java.lang.Double time, java.lang.Double timeReceived, java.lang.Integer unreadSMS) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.unreadSMS = unreadSMS;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return unreadSMS;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: unreadSMS = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'unreadSMS' field.
   * @return number of unread SMS messages currently in the inbox
   */
  public java.lang.Integer getUnreadSMS() {
    return unreadSMS;
  }

  /**
   * Sets the value of the 'unreadSMS' field.
   * number of unread SMS messages currently in the inbox
   * @param value the value to set.
   */
  public void setUnreadSMS(java.lang.Integer value) {
    this.unreadSMS = value;
  }

  /**
   * Creates a new PhoneSmsUnread RecordBuilder.
   * @return A new PhoneSmsUnread RecordBuilder
   */
  public static org.radarcns.phone.PhoneSmsUnread.Builder newBuilder() {
    return new org.radarcns.phone.PhoneSmsUnread.Builder();
  }

  /**
   * Creates a new PhoneSmsUnread RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhoneSmsUnread RecordBuilder
   */
  public static org.radarcns.phone.PhoneSmsUnread.Builder newBuilder(org.radarcns.phone.PhoneSmsUnread.Builder other) {
    return new org.radarcns.phone.PhoneSmsUnread.Builder(other);
  }

  /**
   * Creates a new PhoneSmsUnread RecordBuilder by copying an existing PhoneSmsUnread instance.
   * @param other The existing instance to copy.
   * @return A new PhoneSmsUnread RecordBuilder
   */
  public static org.radarcns.phone.PhoneSmsUnread.Builder newBuilder(org.radarcns.phone.PhoneSmsUnread other) {
    return new org.radarcns.phone.PhoneSmsUnread.Builder(other);
  }

  /**
   * RecordBuilder for PhoneSmsUnread instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneSmsUnread>
    implements org.apache.avro.data.RecordBuilder<PhoneSmsUnread> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** number of unread SMS messages currently in the inbox */
    private int unreadSMS;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.phone.PhoneSmsUnread.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unreadSMS)) {
        this.unreadSMS = data().deepCopy(fields()[2].schema(), other.unreadSMS);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PhoneSmsUnread instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.phone.PhoneSmsUnread other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unreadSMS)) {
        this.unreadSMS = data().deepCopy(fields()[2].schema(), other.unreadSMS);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneSmsUnread.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneSmsUnread.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneSmsUnread.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneSmsUnread.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'unreadSMS' field.
      * number of unread SMS messages currently in the inbox
      * @return The value.
      */
    public java.lang.Integer getUnreadSMS() {
      return unreadSMS;
    }

    /**
      * Sets the value of the 'unreadSMS' field.
      * number of unread SMS messages currently in the inbox
      * @param value The value of 'unreadSMS'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneSmsUnread.Builder setUnreadSMS(int value) {
      validate(fields()[2], value);
      this.unreadSMS = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'unreadSMS' field has been set.
      * number of unread SMS messages currently in the inbox
      * @return True if the 'unreadSMS' field has been set, false otherwise.
      */
    public boolean hasUnreadSMS() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'unreadSMS' field.
      * number of unread SMS messages currently in the inbox
      * @return This builder.
      */
    public org.radarcns.phone.PhoneSmsUnread.Builder clearUnreadSMS() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PhoneSmsUnread build() {
      try {
        PhoneSmsUnread record = new PhoneSmsUnread();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.unreadSMS = fieldSetFlags()[2] ? this.unreadSMS : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
