/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Data from the step counter. */
@org.apache.avro.specific.AvroGenerated
public class PhoneStepCount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9128136569744799876L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneStepCount\",\"namespace\":\"org.radarcns.phone\",\"doc\":\"Data from the step counter.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"steps\",\"type\":\"int\",\"doc\":\"number of steps taken between this and the previous record\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** number of steps taken between this and the previous record */
  @Deprecated public int steps;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhoneStepCount() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param steps number of steps taken between this and the previous record
   */
  public PhoneStepCount(java.lang.Double time, java.lang.Double timeReceived, java.lang.Integer steps) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.steps = steps;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return steps;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: steps = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'steps' field.
   * @return number of steps taken between this and the previous record
   */
  public java.lang.Integer getSteps() {
    return steps;
  }

  /**
   * Sets the value of the 'steps' field.
   * number of steps taken between this and the previous record
   * @param value the value to set.
   */
  public void setSteps(java.lang.Integer value) {
    this.steps = value;
  }

  /**
   * Creates a new PhoneStepCount RecordBuilder.
   * @return A new PhoneStepCount RecordBuilder
   */
  public static org.radarcns.phone.PhoneStepCount.Builder newBuilder() {
    return new org.radarcns.phone.PhoneStepCount.Builder();
  }

  /**
   * Creates a new PhoneStepCount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhoneStepCount RecordBuilder
   */
  public static org.radarcns.phone.PhoneStepCount.Builder newBuilder(org.radarcns.phone.PhoneStepCount.Builder other) {
    return new org.radarcns.phone.PhoneStepCount.Builder(other);
  }

  /**
   * Creates a new PhoneStepCount RecordBuilder by copying an existing PhoneStepCount instance.
   * @param other The existing instance to copy.
   * @return A new PhoneStepCount RecordBuilder
   */
  public static org.radarcns.phone.PhoneStepCount.Builder newBuilder(org.radarcns.phone.PhoneStepCount other) {
    return new org.radarcns.phone.PhoneStepCount.Builder(other);
  }

  /**
   * RecordBuilder for PhoneStepCount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneStepCount>
    implements org.apache.avro.data.RecordBuilder<PhoneStepCount> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** number of steps taken between this and the previous record */
    private int steps;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.phone.PhoneStepCount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.steps)) {
        this.steps = data().deepCopy(fields()[2].schema(), other.steps);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PhoneStepCount instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.phone.PhoneStepCount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.steps)) {
        this.steps = data().deepCopy(fields()[2].schema(), other.steps);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneStepCount.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneStepCount.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneStepCount.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneStepCount.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'steps' field.
      * number of steps taken between this and the previous record
      * @return The value.
      */
    public java.lang.Integer getSteps() {
      return steps;
    }

    /**
      * Sets the value of the 'steps' field.
      * number of steps taken between this and the previous record
      * @param value The value of 'steps'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneStepCount.Builder setSteps(int value) {
      validate(fields()[2], value);
      this.steps = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'steps' field has been set.
      * number of steps taken between this and the previous record
      * @return True if the 'steps' field has been set, false otherwise.
      */
    public boolean hasSteps() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'steps' field.
      * number of steps taken between this and the previous record
      * @return This builder.
      */
    public org.radarcns.phone.PhoneStepCount.Builder clearSteps() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PhoneStepCount build() {
      try {
        PhoneStepCount record = new PhoneStepCount();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.steps = fieldSetFlags()[2] ? this.steps : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
