/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Event for closing or opening an app */
@org.apache.avro.specific.AvroGenerated
public class PhoneUsageEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3563922546689361692L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneUsageEvent\",\"namespace\":\"org.radarcns.phone\",\"doc\":\"Event for closing or opening an app\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"packageName\",\"type\":\"string\",\"doc\":\"package name of the launched app\"},{\"name\":\"className\",\"type\":\"string\",\"doc\":\"class of the view that was launched\"},{\"name\":\"eventType\",\"type\":{\"type\":\"enum\",\"name\":\"UsageEventType\",\"symbols\":[\"FOREGROUND\",\"BACKGROUND\"]},\"doc\":\"whether the event was opening or closing the app\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** package name of the launched app */
  @Deprecated public java.lang.CharSequence packageName;
  /** class of the view that was launched */
  @Deprecated public java.lang.CharSequence className;
  /** whether the event was opening or closing the app */
  @Deprecated public org.radarcns.phone.UsageEventType eventType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhoneUsageEvent() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param packageName package name of the launched app
   * @param className class of the view that was launched
   * @param eventType whether the event was opening or closing the app
   */
  public PhoneUsageEvent(java.lang.Double time, java.lang.Double timeReceived, java.lang.CharSequence packageName, java.lang.CharSequence className, org.radarcns.phone.UsageEventType eventType) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.packageName = packageName;
    this.className = className;
    this.eventType = eventType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return packageName;
    case 3: return className;
    case 4: return eventType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: packageName = (java.lang.CharSequence)value$; break;
    case 3: className = (java.lang.CharSequence)value$; break;
    case 4: eventType = (org.radarcns.phone.UsageEventType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'packageName' field.
   * @return package name of the launched app
   */
  public java.lang.CharSequence getPackageName() {
    return packageName;
  }

  /**
   * Sets the value of the 'packageName' field.
   * package name of the launched app
   * @param value the value to set.
   */
  public void setPackageName(java.lang.CharSequence value) {
    this.packageName = value;
  }

  /**
   * Gets the value of the 'className' field.
   * @return class of the view that was launched
   */
  public java.lang.CharSequence getClassName() {
    return className;
  }

  /**
   * Sets the value of the 'className' field.
   * class of the view that was launched
   * @param value the value to set.
   */
  public void setClassName(java.lang.CharSequence value) {
    this.className = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return whether the event was opening or closing the app
   */
  public org.radarcns.phone.UsageEventType getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * whether the event was opening or closing the app
   * @param value the value to set.
   */
  public void setEventType(org.radarcns.phone.UsageEventType value) {
    this.eventType = value;
  }

  /**
   * Creates a new PhoneUsageEvent RecordBuilder.
   * @return A new PhoneUsageEvent RecordBuilder
   */
  public static org.radarcns.phone.PhoneUsageEvent.Builder newBuilder() {
    return new org.radarcns.phone.PhoneUsageEvent.Builder();
  }

  /**
   * Creates a new PhoneUsageEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhoneUsageEvent RecordBuilder
   */
  public static org.radarcns.phone.PhoneUsageEvent.Builder newBuilder(org.radarcns.phone.PhoneUsageEvent.Builder other) {
    return new org.radarcns.phone.PhoneUsageEvent.Builder(other);
  }

  /**
   * Creates a new PhoneUsageEvent RecordBuilder by copying an existing PhoneUsageEvent instance.
   * @param other The existing instance to copy.
   * @return A new PhoneUsageEvent RecordBuilder
   */
  public static org.radarcns.phone.PhoneUsageEvent.Builder newBuilder(org.radarcns.phone.PhoneUsageEvent other) {
    return new org.radarcns.phone.PhoneUsageEvent.Builder(other);
  }

  /**
   * RecordBuilder for PhoneUsageEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneUsageEvent>
    implements org.apache.avro.data.RecordBuilder<PhoneUsageEvent> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** package name of the launched app */
    private java.lang.CharSequence packageName;
    /** class of the view that was launched */
    private java.lang.CharSequence className;
    /** whether the event was opening or closing the app */
    private org.radarcns.phone.UsageEventType eventType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.phone.PhoneUsageEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.packageName)) {
        this.packageName = data().deepCopy(fields()[2].schema(), other.packageName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.className)) {
        this.className = data().deepCopy(fields()[3].schema(), other.className);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventType)) {
        this.eventType = data().deepCopy(fields()[4].schema(), other.eventType);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PhoneUsageEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.phone.PhoneUsageEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.packageName)) {
        this.packageName = data().deepCopy(fields()[2].schema(), other.packageName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.className)) {
        this.className = data().deepCopy(fields()[3].schema(), other.className);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventType)) {
        this.eventType = data().deepCopy(fields()[4].schema(), other.eventType);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'packageName' field.
      * package name of the launched app
      * @return The value.
      */
    public java.lang.CharSequence getPackageName() {
      return packageName;
    }

    /**
      * Sets the value of the 'packageName' field.
      * package name of the launched app
      * @param value The value of 'packageName'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder setPackageName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.packageName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'packageName' field has been set.
      * package name of the launched app
      * @return True if the 'packageName' field has been set, false otherwise.
      */
    public boolean hasPackageName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'packageName' field.
      * package name of the launched app
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder clearPackageName() {
      packageName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'className' field.
      * class of the view that was launched
      * @return The value.
      */
    public java.lang.CharSequence getClassName() {
      return className;
    }

    /**
      * Sets the value of the 'className' field.
      * class of the view that was launched
      * @param value The value of 'className'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder setClassName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.className = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'className' field has been set.
      * class of the view that was launched
      * @return True if the 'className' field has been set, false otherwise.
      */
    public boolean hasClassName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'className' field.
      * class of the view that was launched
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder clearClassName() {
      className = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * whether the event was opening or closing the app
      * @return The value.
      */
    public org.radarcns.phone.UsageEventType getEventType() {
      return eventType;
    }

    /**
      * Sets the value of the 'eventType' field.
      * whether the event was opening or closing the app
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder setEventType(org.radarcns.phone.UsageEventType value) {
      validate(fields()[4], value);
      this.eventType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * whether the event was opening or closing the app
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'eventType' field.
      * whether the event was opening or closing the app
      * @return This builder.
      */
    public org.radarcns.phone.PhoneUsageEvent.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public PhoneUsageEvent build() {
      try {
        PhoneUsageEvent record = new PhoneUsageEvent();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.packageName = fieldSetFlags()[2] ? this.packageName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.className = fieldSetFlags()[3] ? this.className : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.eventType = fieldSetFlags()[4] ? this.eventType : (org.radarcns.phone.UsageEventType) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
