/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phone;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PhoneInteractionState {
  STANDBY, UNLOCKED, SHUTDOWN, BOOTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PhoneInteractionState\",\"namespace\":\"org.radarcns.phone\",\"symbols\":[\"STANDBY\",\"UNLOCKED\",\"SHUTDOWN\",\"BOOTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
